version: '3.8'
services:
  db:
    restart: unless-stopped
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=work_with_me_backend
      - POSTGRES_PASSWORD=work_with_me_backend
      - POSTGRES_DB=work_with_me_backend
    networks:
      - app_network

  web:
    restart: unless-stopped
    build: .
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - static:/usr/src/app/posts/static
      - media:/usr/src/app/posts/media

  nginx:
    restart: unless-stopped
    container_name: work_with_me_backend
    build: .nginx
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - web
    networks:
      - app_network
      - server


networks:
  app_network:
    driver: bridge
  server:
    external: true

volumes:
  postgres_data:
  static:
  media: