version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn Djoker.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - app_network
      - server
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cyber_garden_django
      - POSTGRES_PASSWORD=cyber_garden_django
      - POSTGRES_DB=cyber_garden_django
    networks:
      - app_network
  nginx:
    container_name: cyber_garden_backend
    build: .nginx
    depends_on:
      - web
    networks:
      - app_network
      - server

networks:
  app_network:
    driver: bridge
  server:
    external: true

volumes:
  postgres_data: