# Generated by Django 3.2.3 on 2021-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('last_name', models.TextField()),
                ('patronimyc', models.TextField()),
                ('type', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('organization', models.TextField()),
                ('avatar_image', models.TextField()),
            ],
        ),
    ]
