# Generated by Django 3.1.5 on 2021-11-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('activity', models.TextField()),
                ('date', models.IntegerField()),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('category', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Recrut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('project', models.TextField()),
                ('date', models.IntegerField()),
                ('period', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('last_name', models.TextField()),
                ('patronimyc', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('organization', models.TextField(default='')),
                ('position', models.TextField(default='')),
                ('contacts', models.TextField(default='')),
                ('avatar_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ManyToManyField(to='Blok.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='recruts',
            field=models.ManyToManyField(to='Blok.Recrut'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='Blok.Tag'),
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.user')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('date_start', models.IntegerField(default=0)),
                ('date_finish', models.IntegerField(default=0)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.column')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('file', models.TextField()),
                ('date', models.IntegerField(default=0)),
                ('type', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blok.user')),
            ],
        ),
    ]
