# Generated by Django 3.2.3 on 2021-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/avatars')),
            ],
        ),
    ]
