# Generated by Django 3.1.5 on 2021-11-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blok', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('description', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Blok.user')),
                ('name', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blok.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronimyc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ManyToManyField(to='Blok.User'),
        ),
    ]
