# Generated by Django 3.1.5 on 2021-11-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blok', '0004_auto_20211109_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='file',
            field=models.FileField(null=True, upload_to='activities'),
        ),
    ]
