name: deploy

on:
  push:
    branches:
      - main
      - master
      - deploy
  pull_request:
    branches:
      - main
      - master
      - deploy

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Deploy 🚀
        run: docker-compose up -d --build
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
